#端口号
server:
  port: 8080
#  servlet:
#    context-path: /tx

#数据库链接
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver                                                        #时区
    url: jdbc:mysql://localhost:3306/dr?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC
    username: root
    password: root
  redis:
    host: 106.13.21.99
    port: 6379
    password:
       pool:
         max-active: 8
         max-idle: 5
         max-wait: 1ms
  thymeleaf:
    cache: false   #关闭缓存

mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: cn.dr.zcw.entity  # 注意：对应实体类的路径
  configuration:
    auto-mapping-behavior: full         #映射级别

#mybatis-plus:

#book:
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
